# Generated by Django 2.2.4 on 2021-06-04 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='p_pic',
            field=models.URLField(max_length=255),
        ),
    ]
