# Generated by Django 2.2.4 on 2021-06-05 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_auto_20210604_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='p_pic',
            field=models.URLField(default='https://c1.klipartz.com/pngpicture/554/218/sticker-png-circle-silhouette-user-profile-user-interface-black-head-blackandwhite-logo.png', max_length=255),
        ),
    ]
