# Generated by Django 2.2.4 on 2021-06-03 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=45)),
                ('desc', models.TextField()),
                ('release_date', models.DateField()),
                ('pic_url', models.TextField()),
                ('trailer_url', models.TextField()),
                ('pic_bg', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fav_list', models.ManyToManyField(related_name='liked_a', to='user_app.Users')),
                ('user_id_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='u_anime', to='user_app.Users')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=45)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('anime_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='a_comment', to='animeapp.Animes')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='u_comment', to='user_app.Users')),
            ],
        ),
    ]
