# Generated by Django 2.2.4 on 2021-06-04 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animeapp', '0002_auto_20210604_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='genre',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='anime_category', to='animeapp.Animes'),
            preserve_default=False,
        ),
    ]
