# Generated by Django 2.2.4 on 2021-06-05 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animeapp', '0003_category_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(choices=[('AC', 'Action'), ('AV', 'Adventure'), ('CM', 'Comedy'), ('DR', 'Drama'), ('HO', 'Horror'), ('HS', 'Highschool'), ('MG', 'Magic'), ('SH', 'Shounen'), ('SL', 'Slice of Life'), ('SN', 'Supernatural'), ('SY', 'Psychological')], max_length=2),
        ),
    ]
