# Generated by Django 2.2.4 on 2021-06-05 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animeapp', '0004_auto_20210605_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='animes',
            name='rating',
            field=models.IntegerField(default=None),
        ),
    ]
