# Generated by Django 3.2.4 on 2021-06-05 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animeapp', '0004_auto_20210605_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='animes',
            name='rating',
            field=models.IntegerField(choices=[(0, 'Zero'), (1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five'), (6, 'Six'), (7, 'Seven'), (8, 'Eight'), (9, 'Nine'), (10, 'Ten')], default=0, null=True),
        ),
    ]
