# Generated by Django 2.2.4 on 2021-06-05 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animeapp', '0005_animes_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animes',
            name='rating',
            field=models.IntegerField(null=True),
        ),
    ]
