# Generated by Django 3.2.4 on 2021-06-05 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animeapp', '0009_alter_animes_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='user_id',
            new_name='users_id',
        ),
    ]
